#!/usr/bin/env python3
import os

# Script generado automáticamente para renombrar archivos

directorio = r'/Users/a01234/huertodigital-01234/archivo'

# Realizar los cambios
cambios = {
    'simbolo-0.md': 'simbolo_origen.md',
    '43_estructura.md': 'estructura.md',
    '41_invarianza_estructural.md': 'invarianza_estructural.md',
    'Meta Búsqueda Centralizada.md': 'meta_búsqueda_centralizada.md',
    '1_conciencia.md': 'conciencia.md',
    '40_mistica.md': 'mistica.md',
    '40_mejora_continua.md': 'mejora_continua.md',
    '4_frecuencia.md': 'frecuencia.md',
    '3_index.md': 'indice.md',
    'meta_modelo_01234_PKMs.md': 'meta_modelo_huerto_digital_pkms.md',
    '2_sesgo.md': 'sesgo.md',
    '2_percepcion.md': 'percepcion.md',
    '3_simbolo.md': 'simbolo.md',
    '30_pardes.md': 'pardes_jardin_hermeneutica.md',
    '1.md': 'documento.md',
    '1_elemento.md': 'elemento_basico.md',
    '01234_evocaciones_poeticas.md': 'huerto_digital_evocaciones_poeticas.md',
    'evocaciones-poeticas.md': 'evocaciones_poeticas.md',
    '324_interpretacion.md': 'interpretacion.md',
    '1_discernimiento.md': 'discernimiento.md',
    '1_matriz.md': 'matriz_origen.md',
    '2_autocancelacion.md': 'autocancelacion.md',
    '13_fonema.md': 'fonema.md',
    'simbolo-1.md': 'simbolo_unidad.md',
    '4_cuaternario.md': 'cuaternario.md',
    '43_coagulacion_significado.md': 'coagulacion_significado.md',
    '32_dialogo.md': 'dialogo.md',
    '20_paradoja.md': 'paradoja.md',
    '13_peso.md': 'peso.md',
    'metamodelo-index.md': 'indice_metamodelo.md',
    '32_encuentro.md': 'encuentro.md',
    '1_efecto_aladino.md': 'efecto_aladino.md',
    '2_tension.md': 'tension.md',
    '1_espiritu.md': 'espiritu.md',
    'Estructura Nodal.md': 'estructura_nodal.md',
    'estructura_01234.md': 'estructura_huerto_digital.md',
    '1_razon.md': 'razon.md',
    'esquema_01234_base.md': 'esquema_huerto_digital_base.md',
    '24_dualidad_onda-particula.md': 'dualidad_onda_particula.md',
    '1_nodo_neurona.md': 'nodo_neurona.md',
    '40_despliegue.md': 'despliegue.md',
    'meta_modelo_01234.md': 'meta_modelo_huerto_digital.md',
    '23_impresion_mental.md': 'impresion_mental.md',
    '1_logos.md': 'logos_palabra_creadora.md',
    '023_faceta_como_percepcion.md': 'faceta_como_percepcion.md',
    '3_convergencia.md': 'convergencia.md',
    '4_vibracion.md': 'vibracion.md',
    '41_propiedad.md': 'propiedad.md',
    'campo-semantico.md': 'campo_semantico.md',
    '3_sentido.md': 'sentido.md',
    '3_contexto.md': 'contexto.md',
    '41_evidencia.md': 'evidencia.md',
    '41_pkm.md': 'gestion_conocimiento_personal.md',
    '34_arte.md': 'arte.md',
    '1_luz.md': 'luz.md',
    '01234_huerto_digital.md': 'huerto_digital_huerto_digital.md',
    '14_lugaritmo.md': 'lugaritmo.md',
    '3_tetractys.md': 'tetractys.md',
    '3_onda.md': 'onda.md',
    '14_cosa.md': 'cosa.md',
    '1_existencia.md': 'existencia.md',
    '1_idea.md': 'idea.md',
    'diagrama-01234.md': 'diagrama_huerto_digital.md',
    '04_causa_efecto.md': 'causa_efecto.md',
    '1_captura_informacion.md': 'captura_informacion.md',
    '1_realidad.md': 'realidad.md',
    '43_literal.md': 'literal.md',
    '10_creacion.md': 'creacion.md',
    '4_particula.md': 'particula.md',
    '1_concepto.md': 'concepto.md',
    '2_reshimo.md': 'reshimo_huella.md',
    '43_aaas.md': 'agentes_como_servicio.md',
    '01234.md': 'huerto_digital.md',
    '31_sinapsis.md': 'sinapsis.md',
    'alignment.md': 'alineamiento.md',
    '1_observacion.md': 'observacion.md',
    '4_olam.md': 'olam_mundo.md',
    '4_accion.md': 'accion.md',
    '1_sujeto.md': 'sujeto.md',
    '2_sinergia.md': 'sinergia.md',
    '4_vida.md': 'vida.md',
    '3_mapa.md': 'mapa.md',
    '3_tetragramaton.md': 'tetragramaton.md',
    '0_depuracion.md': 'depuracion.md',
    '1_sintesis.md': 'sintesis.md',
    '1_universo.md': 'universo.md',
    '13_pnl.md': 'programacion_neurolinguistica.md',
    'que_es_01234.md': 'que_es_huerto_digital.md',
    '30_poesia.md': 'poesia.md',
    '3_significado.md': 'significado.md',
    'perfil-sergiofores.md': 'perfil_sergiofores.md',
    '1_darse_cuenta.md': 'darse_cuenta.md',
    '1_arje.md': 'principio_fundamental.md',
    'frases_clave_01234.md': 'frases_clave_huerto_digital.md',
    '1_basb.md': 'construccion_segundo_cerebro.md',
    '3_mente.md': 'mente.md',
    '3_explica.md': 'explicacion.md',
    '341_red_coherente_conocimiento.md': 'red_coherente_conocimiento.md',
    '3_conectivo.md': 'conectivo.md',
    'codigo.md': 'codigo_fuente.md',
    '4_objeto.md': 'objeto.md',
    '4_cuerpo.md': 'cuerpo.md',
    '34_informacion.md': 'informacion.md',
    '43_hermeneutica.md': 'hermeneutica.md',
    'simbolo-2.md': 'simbolo_dualidad.md',
    '3_vinculo.md': 'vinculo.md',
    '44_recurso.md': 'recurso.md',
    '1_orden.md': 'orden.md',
    '10_inteligencia.md': 'inteligencia.md',
    '0_info_proyecto.md': 'info_proyecto.md',
    '30_cognicion_extendida.md': 'cognicion_extendida.md',
    '1_modelo.md': 'modelo.md',
    '3_concatenacion.md': 'concatenacion.md',
    '3_palabra.md': 'palabra.md',
    '10_insight.md': 'insight_revelacion.md',
    '40_ahora.md': 'ahora_presente.md',
    '41_coherencia_esencial.md': 'coherencia_esencial.md',
    '40_fin.md': 'fin.md',
    '4_resultado.md': 'resultado.md',
    '3_sistema.md': 'sistema.md',
    '0_info_sergiofores.md': 'info_sergiofores.md',
    '31_cognicion.md': 'cognicion.md',
    '34_termino.md': 'termino.md',
    '33_mapa_mental.md': 'mapa_mental.md',
    '30_llm.md': 'modelos_lenguaje.md',
    '240_kli.md': 'kli.md',
    '40_proceso.md': 'proceso.md',
    '04_contemplacion.md': 'contemplacion_1.md',
    '2_index.md': 'indice_1.md',
    '0_preexistencia.md': 'preexistencia_1.md',
    '0.md': 'documento_1.md',
    '4.md': 'documento_2.md',
    '02_dominio.md': 'dominio_1.md',
    '4_index.md': 'indice_2.md',
    '03_campo_semantico.md': 'campo_semantico_1.md',
    'README.md': 'readme_1.md',
    '2_faceta.md': 'faceta_1.md',
    'causa-efecto.md': 'causa_efecto_1.md',
    'index.md': 'indice_3.md',
    '04_gradiente.md': 'gradiente_1.md',
    '0_index.md': 'indice_4.md',
    '1_index.md': 'indice_5.md',
    '01_latencia.md': 'latencia_1.md',
    '3.md': 'documento_3.md',
    '12_percepcion.md': 'percepcion_1.md',
    '0_repositorio.md': 'repositorio_1.md',
    '0_codigo.md': 'codigo_fuente_1.md',
    '2.md': 'documento_4.md',
}

# Ejecutar los cambios
for original, nuevo in cambios.items():
    ruta_original = os.path.join(directorio, original)
    ruta_nueva = os.path.join(directorio, nuevo)
    try:
        os.rename(ruta_original, ruta_nueva)
        print(f'Renombrado: {original} -> {nuevo}')
    except Exception as e:
        print(f'Error al renombrar {original}: {e}')
